name: CI - Task Tracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout code
      uses: actions/checkout@v3

    - name: 🧪 Run test (basic dummy test)
      run: |
        echo "Running basic test..."
        echo "Task Tracker CI successful!"
